packages:
  - apps/*
  - packages/*
  - packages/plugins/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalogs:
  medusa:
    "@medusajs/deps": ^2.10.3
    "@medusajs/telemetry": ^2.10.3
    "@medusajs/utils": ^2.10.3
    "@medusajs/framework": ^2.10.3
    "@medusajs/core-flows": ^2.10.3
  dev:
    "@antfu/eslint-config": ^5.4.1
    "@eslint-react/eslint-plugin": ^1.52.6
    "@swc/core": 1.5.7
    "@tailwindcss/postcss": ^4.1.11
    "@turbo/gen": ^2.5.5
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    hookable: ^5.5.3
    nitro: npm:nitro-nightly
    unbuild: 3.6.1
    unimport: ^5.4.1
    tailwindcss: ^4.1.11
    typescript: ^5.9.2
  cli:
    "@antfu/ni": ^26.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.4
    tsx: ^4.20.5
    typescript: ^5.9.2
    vite: ^7.1.7
  inlined:
    "@antfu/utils": ^9.2.1
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    "@medusajs/types": 2.10.3
    "@types/express": ^4.17.17
    "@types/node": ^24.5.2
    "@types/react": ^19.1.9
    "@types/react-dom": ^19.1.7
    "@types/qs": ^6.14.0
    "@types/request-ip": ^0.0.41
    "@types/yargs": ^15.0.15
    "@types/node-schedule": ^2.1.8
  common:
    "@adonisjs/fold": ^10.2.0
    citty: ^0.1.6
    chokidar: ^3.4.2
    consola: ^3.4.2
    dotenv: ^16.4.5
    dotenv-expand: ^11.0.6
    execa: ^8.0.1
    express: ^4.21.0
    errx: ^0.1.0
    exsolve: ^1.0.7
    fs-exists-cached: ^1.0.0
    fs-extra: ^11.2.0
    is-valid-path: ^0.1.1
    jiti: ^2.6.1
    mlly: ^1.8.0
    node-schedule: ^2.1.1
    pathe: ^2.0.3
    pg-god: ^1.0.12
    prompts: ^2.4.2
    qs: ^6.11.2
    request-ip: ^3.3.0
    tinyglobby: ^0.2.15
    uuid: ^9.0.0
    yargs: ^15.3.1
  conflicts_types_h20_19_9:
    "@types/node": ^20.19.9
  conflicts_react_h18_2_0:
    react: ^18.2.0
  conflicts_react-dom_h18_2_0:
    react-dom: ^18.2.0
  conflicts_zod_3_25_76:
    zod: 3.25.76
  conflicts_types_h20_11_15:
    "@types/node": ^20.11.15
  conflicts_types_h18_2_79:
    "@types/react": ^18.2.79
  conflicts_types_h18_2_25:
    "@types/react-dom": ^18.2.25
  conflicts_dev_h3_4_1:
    tailwindcss: ^3.4.1
  conflicts_dev_5_2_2:
    typescript: 5.2.2
  conflicts_cli_h5_4_14:
    vite: ^5.4.14
  conflicts_testing_h3_0_5:
    vitest: ^3.0.5
  conflicts_conflicts_react_h18_2_0_h19_1_1:
    react: ^19.1.1
  conflicts_conflicts_react-dom_h18_2_0_h19_1_1:
    react-dom: ^19.1.1
  conflicts_testing_3_2_4:
    vitest: 3.2.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
catalog:
  "@adonisjs/fold": ^10.2.0
  "@ariakit/react": ^0.4.15
  "@dnd-kit/core": ^6.1.0
  "@dnd-kit/sortable": ^8.0.0
  "@dnd-kit/utilities": ^3.2.2
  "@hookform/error-message": ^2.0.1
  "@hookform/resolvers": 3.4.2
  "@medusajs/admin-shared": 2.10.3
  "@medusajs/admin-vite-plugin": 2.10.3
  "@medusajs/icons": 2.10.3
  "@medusajs/js-sdk": 2.10.3
  "@medusajs/types": 2.10.3
  "@medusajs/ui": 4.0.23
  "@medusajs/ui-preset": 2.10.3
  "@radix-ui/react-dialog": 1.1.4
  "@radix-ui/react-dismissable-layer": 1.1.4
  "@radix-ui/react-slot": ^1.2.3
  "@tanstack/react-query": 5.64.2
  "@tanstack/react-table": 8.20.5
  "@tanstack/react-virtual": ^3.8.3
  "@uiw/react-json-view": ^2.0.0-alpha.17
  "@vitejs/plugin-react": 4.2.1
  ajv: ^8.17.1
  autoprefixer: ^10.4.17
  c12: ^3.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^0.2.0
  copy-to-clipboard: ^3.3.3
  date-fns: ^3.6.0
  errx: ^0.1.0
  exsolve: ^1.0.7
  hookable: 5.5.3
  i18next: 23.7.11
  i18next-browser-languagedetector: 7.2.0
  i18next-http-backend: 2.4.2
  jiti: ^2.6.1
  lodash: ^4.17.21
  lucide-react: ^0.475.0
  match-sorter: ^6.3.4
  mlly: ^1.8.0
  motion: ^11.15.0
  next: ^15.4.5
  next-themes: ^0.4.6
  nitro: npm:nitro-nightly
  pathe: ^2.0.3
  postcss: ^8.4.33
  prettier: ^3.1.1
  qs: ^6.12.0
  radix-ui: 1.1.2
  react: ^19.1.1
  react-country-flag: ^3.1.0
  react-currency-input-field: ^3.6.11
  react-dom: ^19.1.1
  react-helmet-async: ^2.0.5
  react-hook-form: 7.49.1
  react-i18next: 13.5.0
  react-jwt: ^1.2.0
  react-router-dom: 6.20.1
  tailwind-merge: ^3.3.1
  tinyglobby: ^0.2.15
  tsup: ^8.0.2
  tw-animate-css: ^1.3.6
  unbuild: 3.6.1
  unimport: ^5.4.1
  vite-plugin-inspect: ^0.8.7
  zod: ^3.25.76
