packages:
  - apps/*
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalogs:
  dev:
    "@antfu/eslint-config": ^5.4.1
    "@eslint-react/eslint-plugin": ^1.52.6
    "@tailwindcss/postcss": ^4.1.11
    "@turbo/gen": ^2.5.5
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    tailwindcss: ^4.1.11
    typescript: ^5.9.2
  cli:
    "@antfu/ni": ^26.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.4
    tsx: ^4.20.5
    typescript: ^5.9.2
    vite: ^7.1.7
  inlined:
    "@antfu/utils": ^9.2.1
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    "@types/node": ^24.5.2
    "@types/react": ^19.1.9
    "@types/react-dom": ^19.1.7
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
catalog:
  "@radix-ui/react-slot": ^1.2.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  lucide-react: ^0.475.0
  next-themes: ^0.4.6
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwind-merge: ^3.3.1
  tw-animate-css: ^1.3.6
  zod: ^3.25.76
