import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/intro',
        'guides/getting-started',
        'guides/architecture',
        'guides/creating-a-module',
        'guides/conventions',
      ],
    },
  ],
  modulesSidebar: [
    {
      type: 'category',
      label: 'Kit',
      items: [
        'modules/kit/overview',
        'modules/kit/database',
        'modules/kit/graphql',
        'modules/kit/ioc',
        'modules/kit/event-bus',
      ],
    },
    {
      type: 'category',
      label: 'Auth',
      items: [
        'modules/auth/overview',
        'modules/auth/configuration',
        'modules/auth/permissions',
        'modules/auth/apps',
      ],
    },
    {
      type: 'category',
      label: 'Stock Location',
      items: [
        'modules/stock-location/overview',
        'modules/stock-location/mutations',
        'modules/stock-location/events',
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/graphql/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Auth',
      link: { type: 'doc', id: 'api/graphql/auth/index' },
      items: [{ type: 'autogenerated', dirName: 'api/graphql/auth' }],
    },
    {
      type: 'category',
      label: 'Stock Location',
      link: { type: 'doc', id: 'api/graphql/stock-location/index' },
      items: [{ type: 'autogenerated', dirName: 'api/graphql/stock-location' }],
    },
  ],
}

export default sidebars
