/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Images {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: string;
  metadata: Json | null;
  rank: Generated<number>;
  updatedAt: Generated<Timestamp>;
  url: string;
}

export interface PCategories {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: Generated<string>;
  handle: string;
  id: string;
  imageId: string | null;
  isActive: Generated<boolean>;
  isInternal: Generated<boolean>;
  metadata: Json | null;
  name: string;
  parentId: string | null;
  rank: Generated<number>;
  thumbnail: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface PCategoriesProducts {
  pCategoriesId: string;
  productId: string;
}

export interface PCollections {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  handle: string;
  id: string;
  metadata: Json | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface POptions {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: string;
  metadata: Json | null;
  productId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface POptionValues {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: string;
  metadata: Json | null;
  optionId: string | null;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Products {
  collectionId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  discountable: Generated<boolean>;
  externalId: string | null;
  handle: string;
  height: string | null;
  hsCode: string | null;
  id: string;
  isGiftcard: Generated<boolean>;
  length: string | null;
  material: string | null;
  metadata: Json | null;
  midCode: string | null;
  originCountry: string | null;
  status: Generated<string>;
  subtitle: string | null;
  thumbnail: string | null;
  title: string;
  typeId: string | null;
  updatedAt: Generated<Timestamp>;
  weight: string | null;
  width: string | null;
}

export interface ProductsImages {
  imageId: string;
  productId: string;
  variantId: string;
}

export interface ProductsTags {
  productId: string;
  productTagId: string;
}

export interface PTags {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: string;
  metadata: Json | null;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface PTypes {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: string;
  metadata: Json | null;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface PVariants {
  allowBackorder: Generated<boolean>;
  barcode: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  ean: string | null;
  height: number | null;
  hsCode: string | null;
  id: string;
  length: number | null;
  manageInventory: Generated<boolean>;
  material: string | null;
  metadata: Json | null;
  midCode: string | null;
  originCountry: string | null;
  productId: string | null;
  sku: string | null;
  thumbnail: string | null;
  title: string;
  upc: string | null;
  updatedAt: Generated<Timestamp>;
  variantRank: Generated<number | null>;
  weight: number | null;
  width: number | null;
}

export interface PVariantsOptions {
  optionValueId: string;
  variantId: string;
}

export interface Database {
  images: Images;
  pCategories: PCategories;
  pCategoriesProducts: PCategoriesProducts;
  pCollections: PCollections;
  pOptions: POptions;
  pOptionValues: POptionValues;
  products: Products;
  productsImages: ProductsImages;
  productsTags: ProductsTags;
  pTags: PTags;
  pTypes: PTypes;
  pVariants: PVariants;
  pVariantsOptions: PVariantsOptions;
}
