import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  declaration: 'node16',
  entries: [
    'src/index',
    'src/database/schema',
    'src/database/relations',
    'src/services/index',
    'src/graphql/index',
  ],
  externals: [
    '@czo/kit',
    '@czo/kit/module',
    '@czo/kit/db',
    '@czo/kit/graphql',
    '@czo/auth',
    '@czo/auth/services',
    '@czo/auth/graphql',
    '@czo/auth/schema',
    '@czo/attribute',
    '@czo/attribute/services',
    '@czo/attribute/schema',
    '@czo/attribute/relations',
    '@czo/price',
    '@czo/price/services',
    '@czo/price/schema',
    '@czo/price/relations',
    '@czo/inventory',
    '@czo/inventory/services',
    '@czo/inventory/schema',
    '@czo/inventory/relations',
    '@czo/channel',
    '@czo/channel/services',
    '@czo/channel/schema',
    '@czo/channel/relations',
    '@czo/stock-location',
    '@czo/stock-location/services',
    '@czo/stock-location/schema',
    '@czo/stock-location/relations',
    '@czo/translation',
    '@czo/translation/services',
    '@czo/translation/graphql',
    'drizzle-orm',
    'drizzle-orm/pg-core',
  ],
})
