blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question / general discussion
    url: https://github.com/bnofao/c-zo/discussions
    about: Use Discussions for help, design chats, and Q&A.
  - name: 🔒 Security vulnerability report
    url: https://github.com/bnofao/c-zo/security/advisories/new
    about: Please report vulnerabilities privately via Security Advisories.
  - name: 📖 Documentation site
    url: https://c-zo.com
    about: Check the docs; many questions are answered there.