import type { InventoryGraphQLSchemaBuilder, InventoryItemWhereInput } from '@czo/inventory/graphql'
import { z } from 'zod'

// ─── Zod schemas ──────────────────────────────────────────────────────────────

const inventoryItemOrderFieldSchema = z.enum(['sku', 'createdAt'])
const orderDirectionSchema = z.enum(['asc', 'desc'])

// ─── Pothos input types ───────────────────────────────────────────────────────
//
// `CreateInventoryItemInput`, `UpdateInventoryItemInput`, etc. are generated by
// `relayMutationField` from the inline `inputFields` blocks in mutations files
// — no standalone mutation input shapes are needed here.

export function registerInventoryInputs(builder: InventoryGraphQLSchemaBuilder): void {
  const InventoryItemWhereInputRef = builder.inputRef<InventoryItemWhereInput>('InventoryItemWhereInput').implement({
    subGraphs: ['org'],
    description: 'Filter predicate for the `inventoryItems` connection. Field filters are AND-combined; use AND/OR/NOT to compose arbitrary boolean trees.',
    fields: t => ({
      sku: t.field({ type: 'StringFilterInput', description: 'Filter by SKU.' }),
      organizationId: t.field({ type: 'IntFilterInput', description: 'Filter by owning organization id.' }),
      requiresShipping: t.field({ type: 'BooleanFilterInput', description: 'Filter by the requiresShipping flag.' }),
      createdAt: t.field({ type: 'DateTimeFilterInput', description: 'Filter by creation timestamp.' }),
      AND: t.field({ type: [InventoryItemWhereInputRef], description: 'All sub-predicates must match.' }),
      OR: t.field({ type: [InventoryItemWhereInputRef], description: 'At least one sub-predicate must match.' }),
      NOT: t.field({ type: InventoryItemWhereInputRef, description: 'The sub-predicate must not match.' }),
    }),
  })

  const InventoryItemOrderFieldRef = builder.enumType('InventoryItemOrderField', {
    subGraphs: ['org'],
    description: 'A field the `inventoryItems` connection can be ordered by.',
    values: {
      SKU: { value: 'sku' },
      CREATED_AT: { value: 'createdAt' },
    } as const,
  })

  // Own the sort-direction enum locally rather than referencing auth's
  // `OrderDirection` by string name — that coupled the schema build to auth's
  // contribution running first and never type-checked across modules.
  const InventoryItemOrderDirectionRef = builder.enumType('InventoryItemOrderDirection', {
    subGraphs: ['org'],
    description: 'Sort direction: ascending or descending.',
    values: {
      ASC: { value: 'asc' },
      DESC: { value: 'desc' },
    } as const,
  })

  builder.inputType('InventoryItemOrderByInput', {
    subGraphs: ['org'],
    description: 'One ordering clause for the `inventoryItems` connection (field + direction). Multiple clauses are applied in order.',
    fields: t => ({
      field: t.field({ type: InventoryItemOrderFieldRef, required: true, validate: inventoryItemOrderFieldSchema, description: 'The item field to sort by.' }),
      direction: t.field({ type: InventoryItemOrderDirectionRef, required: true, validate: orderDirectionSchema, description: 'Ascending or descending.' }),
    }),
  })
}
