import type { InventoryGraphQLSchemaBuilder, InventoryItemWhereInput } from '@czo/inventory/graphql'
import { z } from 'zod'

// ─── Zod schemas ──────────────────────────────────────────────────────────────

const inventoryItemOrderFieldSchema = z.enum(['sku', 'createdAt'])
const orderDirectionSchema = z.enum(['asc', 'desc'])

// ─── Pothos input types ───────────────────────────────────────────────────────
//
// `CreateInventoryItemInput`, `UpdateInventoryItemInput`, etc. are generated by
// `relayMutationField` from the inline `inputFields` blocks in mutations files
// — no standalone mutation input shapes are needed here.

export function registerInventoryInputs(builder: InventoryGraphQLSchemaBuilder): void {
  const InventoryItemWhereInputRef = builder.inputRef<InventoryItemWhereInput>('InventoryItemWhereInput').implement({
    fields: t => ({
      sku: t.field({ type: 'StringFilterInput' }),
      organizationId: t.field({ type: 'IntFilterInput' }),
      requiresShipping: t.field({ type: 'BooleanFilterInput' }),
      createdAt: t.field({ type: 'DateTimeFilterInput' }),
      AND: t.field({ type: [InventoryItemWhereInputRef] }),
      OR: t.field({ type: [InventoryItemWhereInputRef] }),
      NOT: t.field({ type: InventoryItemWhereInputRef }),
    }),
  })

  const InventoryItemOrderFieldRef = builder.enumType('InventoryItemOrderField', {
    values: {
      SKU: { value: 'sku' },
      CREATED_AT: { value: 'createdAt' },
    } as const,
  })

  // Own the sort-direction enum locally rather than referencing auth's
  // `OrderDirection` by string name — that coupled the schema build to auth's
  // contribution running first and never type-checked across modules.
  const InventoryItemOrderDirectionRef = builder.enumType('InventoryItemOrderDirection', {
    values: {
      ASC: { value: 'asc' },
      DESC: { value: 'desc' },
    } as const,
  })

  builder.inputType('InventoryItemOrderByInput', {
    fields: t => ({
      field: t.field({ type: InventoryItemOrderFieldRef, required: true, validate: inventoryItemOrderFieldSchema }),
      direction: t.field({ type: InventoryItemOrderDirectionRef, required: true, validate: orderDirectionSchema }),
    }),
  })
}
