import type { ChannelGraphQLSchemaBuilder, ChannelWhereInput } from '@czo/channel/graphql'
import { z } from 'zod'

// ─── Zod schemas ──────────────────────────────────────────────────────────────

const channelOrderFieldSchema = z.enum(['name', 'handle', 'createdAt'])
const orderDirectionSchema = z.enum(['asc', 'desc'])

// ─── Pothos input types ───────────────────────────────────────────────────────
//
// `CreateChannelInput` and `UpdateChannelInput` are generated by
// `relayMutationField` from the inline `inputFields` blocks in mutations.ts
// — no standalone mutation input shapes are needed here.

export function registerChannelInputs(builder: ChannelGraphQLSchemaBuilder): void {
  const ChannelWhereInputRef = builder.inputRef<ChannelWhereInput>('ChannelWhereInput').implement({
    fields: t => ({
      name: t.field({ type: 'StringFilterInput' }),
      handle: t.field({ type: 'StringFilterInput' }),
      organizationId: t.field({ type: 'IntFilterInput' }),
      isActive: t.field({ type: 'BooleanFilterInput' }),
      isDefault: t.field({ type: 'BooleanFilterInput' }),
      createdAt: t.field({ type: 'DateTimeFilterInput' }),
      AND: t.field({ type: [ChannelWhereInputRef] }),
      OR: t.field({ type: [ChannelWhereInputRef] }),
      NOT: t.field({ type: ChannelWhereInputRef }),
    }),
  })

  const ChannelOrderFieldRef = builder.enumType('ChannelOrderField', {
    values: {
      NAME: { value: 'name' },
      HANDLE: { value: 'handle' },
      CREATED_AT: { value: 'createdAt' },
    } as const,
  })

  // Own the sort-direction enum locally rather than referencing auth's
  // `OrderDirection` by string name — that coupled the schema build to auth's
  // contribution running first and never type-checked across modules.
  const ChannelOrderDirectionRef = builder.enumType('ChannelOrderDirection', {
    values: {
      ASC: { value: 'asc' },
      DESC: { value: 'desc' },
    } as const,
  })

  builder.inputType('ChannelOrderByInput', {
    fields: t => ({
      field: t.field({ type: ChannelOrderFieldRef, required: true, validate: channelOrderFieldSchema }),
      direction: t.field({ type: ChannelOrderDirectionRef, required: true, validate: orderDirectionSchema }),
    }),
  })
}
