import type { ChannelGraphQLSchemaBuilder, ChannelWhereInput } from '@czo/channel/graphql'
import { z } from 'zod'

// ─── Zod schemas ──────────────────────────────────────────────────────────────

const channelOrderFieldSchema = z.enum(['name', 'handle', 'createdAt'])
const orderDirectionSchema = z.enum(['asc', 'desc'])

// ─── Pothos input types ───────────────────────────────────────────────────────
//
// `CreateChannelInput` and `UpdateChannelInput` are generated by
// `relayMutationField` from the inline `inputFields` blocks in mutations.ts
// — no standalone mutation input shapes are needed here.

export function registerChannelInputs(builder: ChannelGraphQLSchemaBuilder): void {
  const ChannelWhereInputRef = builder.inputRef<ChannelWhereInput>('ChannelWhereInput').implement({
    subGraphs: ['org', 'admin'],
    description: 'Filter predicate for the `channels` connection. Field filters are AND-combined; use AND/OR/NOT to compose arbitrary boolean trees.',
    fields: t => ({
      name: t.field({ type: 'StringFilterInput', description: 'Filter by channel name.' }),
      handle: t.field({ type: 'StringFilterInput', description: 'Filter by channel handle.' }),
      organizationId: t.field({ type: 'IntFilterInput', description: 'Filter by owning organization id.' }),
      isActive: t.field({ type: 'BooleanFilterInput', description: 'Filter by active state.' }),
      isDefault: t.field({ type: 'BooleanFilterInput', description: 'Filter by default-channel flag.' }),
      createdAt: t.field({ type: 'DateTimeFilterInput', description: 'Filter by creation timestamp.' }),
      AND: t.field({ type: [ChannelWhereInputRef], description: 'All sub-predicates must match.' }),
      OR: t.field({ type: [ChannelWhereInputRef], description: 'At least one sub-predicate must match.' }),
      NOT: t.field({ type: ChannelWhereInputRef, description: 'The sub-predicate must not match.' }),
    }),
  })

  const ChannelOrderFieldRef = builder.enumType('ChannelOrderField', {
    subGraphs: ['org', 'admin'],
    description: 'A field the `channels` connection can be ordered by.',
    values: {
      NAME: { value: 'name' },
      HANDLE: { value: 'handle' },
      CREATED_AT: { value: 'createdAt' },
    } as const,
  })

  // Own the sort-direction enum locally rather than referencing auth's
  // `OrderDirection` by string name — that coupled the schema build to auth's
  // contribution running first and never type-checked across modules.
  const ChannelOrderDirectionRef = builder.enumType('ChannelOrderDirection', {
    subGraphs: ['org', 'admin'],
    description: 'Sort direction: ascending or descending.',
    values: {
      ASC: { value: 'asc' },
      DESC: { value: 'desc' },
    } as const,
  })

  builder.inputType('ChannelOrderByInput', {
    subGraphs: ['org', 'admin'],
    description: 'One ordering clause for the `channels` connection (field + direction). Multiple clauses are applied in order.',
    fields: t => ({
      field: t.field({ type: ChannelOrderFieldRef, required: true, validate: channelOrderFieldSchema, description: 'The channel field to sort by.' }),
      direction: t.field({ type: ChannelOrderDirectionRef, required: true, validate: orderDirectionSchema, description: 'Ascending or descending.' }),
    }),
  })
}
