import { config } from '@workspace/eslint-config/react-internal'

// shadcn/ui components are generated source (regenerated by the CLI), so relax
// the lint rules that their idioms trip: `*Variants` (cva) exports alongside the
// component, and unannotated `<button>`s inside primitives.
export default config.append({
  files: ['src/components/**/*.tsx', 'src/hooks/**/*.ts'],
  rules: {
    'react-refresh/only-export-components': 'off',
    'react-dom/no-missing-button-type': 'off',
    // Base UI's `<X.Provider>` (e.g. Tooltip.Provider) is a component, not a
    // React Context — this rule misfires on it and its autofix breaks the code.
    'react/no-context-provider': 'off',
    'react-hooks-extra/no-direct-set-state-in-use-effect': 'off',
    // Calendar passes inline render components to react-day-picker's slot props;
    // toggle-group builds its context value inline — both are upstream idioms.
    'react/no-nested-component-definitions': 'off',
    'react/no-unstable-context-value': 'off',
  },
})
