export {}
declare global {
  const $fetch: typeof import('nitro/deps/ofetch').$fetch
  const appendCorsHeaders: typeof import('h3').appendCorsHeaders
  const appendCorsPreflightHeaders: typeof import('h3').appendCorsPreflightHeaders
  const appendHeader: typeof import('h3').appendHeader
  const appendHeaders: typeof import('h3').appendHeaders
  const appendResponseHeader: typeof import('h3').appendResponseHeader
  const appendResponseHeaders: typeof import('h3').appendResponseHeaders
  const assertBodySize: typeof import('h3').assertBodySize
  const assertMethod: typeof import('h3').assertMethod
  const basicAuth: typeof import('h3').basicAuth
  const bodyLimit: typeof import('h3').bodyLimit
  const cachedEventHandler: typeof import('nitro/runtime/internal/cache').cachedEventHandler
  const cachedFunction: typeof import('nitro/runtime/internal/cache').cachedFunction
  const callMiddleware: typeof import('h3').callMiddleware
  const clearResponseHeaders: typeof import('h3').clearResponseHeaders
  const clearSession: typeof import('h3').clearSession
  const createApp: typeof import('h3').createApp
  const createError: typeof import('h3').createError
  const createEventStream: typeof import('h3').createEventStream
  const createRouter: typeof import('h3').createRouter
  const defaultContentType: typeof import('h3').defaultContentType
  const defineCachedEventHandler: typeof import('nitro/runtime/internal/cache').defineCachedEventHandler
  const defineCachedFunction: typeof import('nitro/runtime/internal/cache').defineCachedFunction
  const defineCachedHandler: typeof import('nitro/runtime/internal/cache').defineCachedHandler
  const defineEventHandler: typeof import('h3').defineEventHandler
  const defineHandler: typeof import('h3').defineHandler
  const defineLazyEventHandler: typeof import('h3').defineLazyEventHandler
  const defineMiddleware: typeof import('h3').defineMiddleware
  const defineNitroErrorHandler: typeof import('nitro/runtime/internal/error/utils').defineNitroErrorHandler
  const defineNitroPlugin: typeof import('nitro/runtime/internal/plugin').defineNitroPlugin
  const defineNodeHandler: typeof import('h3').defineNodeHandler
  const defineNodeListener: typeof import('h3').defineNodeListener
  const defineNodeMiddleware: typeof import('h3').defineNodeMiddleware
  const definePlugin: typeof import('h3').definePlugin
  const defineRenderHandler: typeof import('nitro/runtime/internal/renderer').defineRenderHandler
  const defineRoute: typeof import('h3').defineRoute
  const defineRouteMeta: typeof import('nitro/runtime/internal/meta').defineRouteMeta
  const defineTask: typeof import('nitro/runtime/internal/task').defineTask
  const defineValidatedHandler: typeof import('h3').defineValidatedHandler
  const defineWebSocket: typeof import('h3').defineWebSocket
  const defineWebSocketHandler: typeof import('h3').defineWebSocketHandler
  const deleteChunkedCookie: typeof import('h3').deleteChunkedCookie
  const deleteCookie: typeof import('h3').deleteCookie
  const dynamicEventHandler: typeof import('h3').dynamicEventHandler
  const eventHandler: typeof import('h3').eventHandler
  const fetchWithEvent: typeof import('h3').fetchWithEvent
  const fromNodeHandler: typeof import('h3').fromNodeHandler
  const fromNodeMiddleware: typeof import('h3').fromNodeMiddleware
  const fromWebHandler: typeof import('h3').fromWebHandler
  const getBodyStream: typeof import('h3').getBodyStream
  const getChunkedCookie: typeof import('h3').getChunkedCookie
  const getCookie: typeof import('h3').getCookie
  const getEventContext: typeof import('h3').getEventContext
  const getHeader: typeof import('h3').getHeader
  const getHeaders: typeof import('h3').getHeaders
  const getMethod: typeof import('h3').getMethod
  const getProxyRequestHeaders: typeof import('h3').getProxyRequestHeaders
  const getQuery: typeof import('h3').getQuery
  const getRequestFingerprint: typeof import('h3').getRequestFingerprint
  const getRequestHeader: typeof import('h3').getRequestHeader
  const getRequestHeaders: typeof import('h3').getRequestHeaders
  const getRequestHost: typeof import('h3').getRequestHost
  const getRequestIP: typeof import('h3').getRequestIP
  const getRequestPath: typeof import('h3').getRequestPath
  const getRequestProtocol: typeof import('h3').getRequestProtocol
  const getRequestURL: typeof import('h3').getRequestURL
  const getRequestWebStream: typeof import('h3').getRequestWebStream
  const getResponseHeader: typeof import('h3').getResponseHeader
  const getResponseHeaders: typeof import('h3').getResponseHeaders
  const getResponseStatus: typeof import('h3').getResponseStatus
  const getResponseStatusText: typeof import('h3').getResponseStatusText
  const getRouteRules: typeof import('nitro/runtime/internal/route-rules').getRouteRules
  const getRouterParam: typeof import('h3').getRouterParam
  const getRouterParams: typeof import('h3').getRouterParams
  const getSession: typeof import('h3').getSession
  const getValidatedQuery: typeof import('h3').getValidatedQuery
  const getValidatedRouterParams: typeof import('h3').getValidatedRouterParams
  const handleCacheHeaders: typeof import('h3').handleCacheHeaders
  const handleCors: typeof import('h3').handleCors
  const html: typeof import('h3').html
  const isCorsOriginAllowed: typeof import('h3').isCorsOriginAllowed
  const isError: typeof import('h3').isError
  const isEvent: typeof import('h3').isEvent
  const isHTTPEvent: typeof import('h3').isHTTPEvent
  const isMethod: typeof import('h3').isMethod
  const isPreflightRequest: typeof import('h3').isPreflightRequest
  const iterable: typeof import('h3').iterable
  const lazyEventHandler: typeof import('h3').lazyEventHandler
  const mockEvent: typeof import('h3').mockEvent
  const nitroPlugin: typeof import('nitro/runtime/internal/plugin').nitroPlugin
  const noContent: typeof import('h3').noContent
  const onError: typeof import('h3').onError
  const onRequest: typeof import('h3').onRequest
  const onResponse: typeof import('h3').onResponse
  const parseCookies: typeof import('h3').parseCookies
  const proxy: typeof import('h3').proxy
  const proxyRequest: typeof import('h3').proxyRequest
  const readBody: typeof import('h3').readBody
  const readFormData: typeof import('h3').readFormData
  const readFormDataBody: typeof import('h3').readFormDataBody
  const readMultipartFormData: typeof import('h3').readMultipartFormData
  const readRawBody: typeof import('h3').readRawBody
  const readValidatedBody: typeof import('h3').readValidatedBody
  const redirect: typeof import('h3').redirect
  const registeredResolvers: typeof import('@czo/kit/graphql').registeredResolvers
  const registeredTypeDefs: typeof import('@czo/kit/graphql').registeredTypeDefs
  const removeResponseHeader: typeof import('h3').removeResponseHeader
  const requireBasicAuth: typeof import('h3').requireBasicAuth
  const runTask: typeof import('nitro/runtime/internal/task').runTask
  const sanitizeStatusCode: typeof import('h3').sanitizeStatusCode
  const sanitizeStatusMessage: typeof import('h3').sanitizeStatusMessage
  const sealSession: typeof import('h3').sealSession
  const sendIterable: typeof import('h3').sendIterable
  const sendNoContent: typeof import('h3').sendNoContent
  const sendProxy: typeof import('h3').sendProxy
  const sendRedirect: typeof import('h3').sendRedirect
  const sendStream: typeof import('h3').sendStream
  const sendWebResponse: typeof import('h3').sendWebResponse
  const serve: typeof import('h3').serve
  const serveStatic: typeof import('h3').serveStatic
  const setChunkedCookie: typeof import('h3').setChunkedCookie
  const setCookie: typeof import('h3').setCookie
  const setHeader: typeof import('h3').setHeader
  const setHeaders: typeof import('h3').setHeaders
  const setResponseHeader: typeof import('h3').setResponseHeader
  const setResponseHeaders: typeof import('h3').setResponseHeaders
  const setResponseStatus: typeof import('h3').setResponseStatus
  const toEventHandler: typeof import('h3').toEventHandler
  const toNodeHandler: typeof import('h3').toNodeHandler
  const toNodeListener: typeof import('h3').toNodeListener
  const toRequest: typeof import('h3').toRequest
  const toResponse: typeof import('h3').toResponse
  const toWebHandler: typeof import('h3').toWebHandler
  const unsealSession: typeof import('h3').unsealSession
  const updateSession: typeof import('h3').updateSession
  const useBase: typeof import('h3').useBase
  const useContainer: typeof import('@czo/kit').useContainer
  const useLogger: typeof import('@czo/kit').useLogger
  const useNitroApp: typeof import('nitro/runtime/internal/app').useNitroApp
  const useRequest: typeof import('nitro/runtime/internal/context').useRequest
  const useRuntimeConfig: typeof import('nitro/runtime/internal/runtime-config').useRuntimeConfig
  const useSession: typeof import('h3').useSession
  const useStorage: typeof import('nitro/runtime/internal/storage').useStorage
  const withBase: typeof import('h3').withBase
  const writeEarlyHints: typeof import('h3').writeEarlyHints
}